---

#
#  ansible-playbook create.yml -i aws
#

- hosts: local
  gather_facts: False
  vars_prompt:
    - name: "key_name"
      prompt: "EC2 access key"
    - name: "db_user"
      prompt: "What is MySQL database username"
    - name: "db_password"
      prompt: "What is MySQL database user password"
      private: yes
  roles:
    - role: wordpress-cloudformation
